name: new

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission to gradlew
        run: chmod +x ./ExpenseTracker-master/gradlew
      - name: Build with Gradle
        run: ./ExpenseTracker-master/gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: AndroidCICD.apk
          path: ExpenseTracker-master/app/build/outputs/apk/debug/app-debug.apk
